### ISSUE TITLE
[Ubuntu] File explorer doesn't display user folders under '/'

### ISSUE THREAD

**Issue by eranbet** [flathub/com.github.Murmele.Gittyup#10]
Local working copies with user ownership residing under '/' are not displayed.
E.g.
1. \>sudo mkdir /bla
2. \> chown user:user /bla
3. \> clone as "user" into /bla (from command-line)
4. Try to open existing repo.
5. The file dialog displays only folders owned by "root" ("bla" isn't displayed)

**Comment by Murmele** [comment]
Hi @eranbet In the flatpak package you have only access to the home folder but not to the root

Maybe you can try to override the permission
```
flatpak-override --filesystem=host com.github.Murmele.Gittyup
```
