### ISSUE TITLE
Unable to right click on files

### ISSUE THREAD

**Issue by RichardFevrier** [flathub/com.github.Murmele.Gittyup#30]
Hi @Murmele please consider reverting the last commit `7c847f53419ea90c365c25bee0ea235d291305515305ca10ae607ca62d0a0d0a`.
Seems broken, I am unable to right click on files (to revert changes for ex) on my system compared to the previous one `8fbb5a180b2fef6f97aae5e78296f2b538748a80e92e403872cee2d010a88949` (I use this one for now on).
Tell me if you need more infos.

**Comment by Murmele** [comment]
Hi @RichardFevrier where are you clicking? For me clicking in the tree view on the right side works fine for me.

**Comment by RichardFevrier** [comment]
Hi @Murmele, I have just updated my Fedora version from 37 to 38 and the issue is not reproductible anymore so I reverted back to the last commit.

**Comment by Murmele** [comment]
Great to hear. Thank you for the feedback
